# app/agents/contracts.py
"""
Agent layer contracts — shared data classes for inter-agent communication.
Defines roles, intent types, task assignments, results, and execution plans.
"""
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List
from datetime import datetime
from enum import Enum


class AgentRole(str, Enum):
    """Roles available in the agent system."""
    ORCHESTRATOR = "orchestrator"
    ADMIN = "admin"
    ASSISTANT = "assistant"
    ARCHITECT = "architect"
    FAST_TRACK = "fast_track"


class IntentType(str, Enum):
    """Classification result for incoming messages."""
    FAST_TRACK = "fast_track"         # Single clear action, low/medium risk
    ADMIN_COMPLEX = "admin_complex"   # Multi-step, needs planning/reasoning
    ASSISTANT = "assistant"            # Q&A, conversation, read-only


class TaskStatus(str, Enum):
    """Execution status of a task."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    SUCCESS = "success"
    FAILED = "failed"
    NEEDS_APPROVAL = "needs_approval"
    TIMEOUT = "timeout"
    DENIED = "denied"


@dataclass
class TaskAssignment:
    """
    Assignment passed from Orchestrator to a sub-agent.
    Contains everything the agent needs to execute.
    """
    trace_id: str
    intent: IntentType
    agent_role: AgentRole
    message: Any  # IncomingMessage (avoid circular import)
    context: Dict[str, Any] = field(default_factory=dict)
    user_role: str = "member"
    guild_id: Optional[int] = None
    session_id: str = ""

    @property
    def prompt(self) -> str:
        """Extract prompt text from message."""
        if hasattr(self.message, "prompt"):
            return self.message.prompt
        return str(self.message)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "trace_id": self.trace_id,
            "intent": self.intent.value,
            "agent_role": self.agent_role.value,
            "user_role": self.user_role,
            "guild_id": self.guild_id,
            "session_id": self.session_id,
        }


@dataclass
class TaskResult:
    """
    Result returned by any agent after execution.
    """
    trace_id: str
    content: str
    status: str = "success"  # success | failed | needs_approval | denied
    tools_called: List[str] = field(default_factory=list)
    cost: Dict[str, Any] = field(default_factory=dict)
    approval_required: bool = False
    approval_id: str = ""
    iterations: int = 0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "trace_id": self.trace_id,
            "content": self.content,
            "status": self.status,
            "tools_called": self.tools_called,
            "cost": self.cost,
            "approval_required": self.approval_required,
            "approval_id": self.approval_id,
        }


@dataclass
class PlanStep:
    """A single step in an execution plan."""
    action: str
    tool_name: str
    params: Dict[str, Any] = field(default_factory=dict)
    risk_level: str = "low"  # low | medium | high | critical
    status: str = "pending"  # pending | executing | done | failed | skipped
    result: Optional[str] = None
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action": self.action,
            "tool_name": self.tool_name,
            "params": self.params,
            "risk_level": self.risk_level,
            "status": self.status,
        }


@dataclass
class ExecutionPlan:
    """
    Multi-step execution plan generated by AdminAgent.
    Subject to HITL approval if contains high/critical risk steps.
    """
    steps: List[PlanStep] = field(default_factory=list)
    total_risk: str = "low"  # Highest risk level among all steps
    requires_approval: bool = False
    approval_id: str = ""
    created_at: float = field(default_factory=lambda: datetime.now().timestamp())

    @property
    def step_count(self) -> int:
        return len(self.steps)

    @property
    def completed_steps(self) -> int:
        return sum(1 for s in self.steps if s.status == "done")

    @property
    def failed_steps(self) -> int:
        return sum(1 for s in self.steps if s.status == "failed")

    def get_pending_steps(self) -> List[PlanStep]:
        """Get steps that haven't been executed yet."""
        return [s for s in self.steps if s.status == "pending"]

    def compute_risk(self) -> str:
        """Compute overall risk from individual steps."""
        risk_levels = {"low": 0, "medium": 1, "high": 2, "critical": 3}
        max_risk = 0
        for step in self.steps:
            level = risk_levels.get(step.risk_level, 0)
            if level > max_risk:
                max_risk = level
        risk_names = {0: "low", 1: "medium", 2: "high", 3: "critical"}
        self.total_risk = risk_names[max_risk]
        self.requires_approval = max_risk >= 2  # high or critical
        return self.total_risk

    def to_dict(self) -> Dict[str, Any]:
        return {
            "steps": [s.to_dict() for s in self.steps],
            "total_risk": self.total_risk,
            "requires_approval": self.requires_approval,
            "approval_id": self.approval_id,
            "step_count": self.step_count,
            "completed": self.completed_steps,
        }
